// Seed данные для popular_destinations
// Источник: топ-направления российского туризма 2025-2026 + глобальные хиты

export interface DestinationSeed {
  nameRu: string;
  aliases?: string;
  type: 'city' | 'resort' | 'airport' | 'region' | 'country' | 'island';
  countryCode: string;
  displayName: string;
  lon: number;
  lat: number;
  popularity: number;
}

export const DESTINATIONS: DestinationSeed[] = [
  // ─── РОССИЯ — крупные города ─────────────────────────────────────────────
  {
    nameRu: 'Москва',
    aliases: 'Moscow,Moskva',
    type: 'city',
    countryCode: 'RU',
    displayName: 'Москва, Россия',
    lon: 37.6173,
    lat: 55.7558,
    popularity: 10.0,
  },
  {
    nameRu: 'Санкт-Петербург',
    aliases: 'Saint Petersburg,SPb,Питер,Ленинград',
    type: 'city',
    countryCode: 'RU',
    displayName: 'Санкт-Петербург, Россия',
    lon: 30.3158,
    lat: 59.9386,
    popularity: 9.5,
  },
  {
    nameRu: 'Сочи',
    aliases: 'Sochi',
    type: 'city',
    countryCode: 'RU',
    displayName: 'Сочи, Краснодарский край, Россия',
    lon: 39.7257,
    lat: 43.6028,
    popularity: 9.0,
  },
  {
    nameRu: 'Казань',
    aliases: 'Kazan',
    type: 'city',
    countryCode: 'RU',
    displayName: 'Казань, Татарстан, Россия',
    lon: 49.1221,
    lat: 55.7887,
    popularity: 8.5,
  },
  {
    nameRu: 'Екатеринбург',
    aliases: 'Yekaterinburg,Ekaterinburg',
    type: 'city',
    countryCode: 'RU',
    displayName: 'Екатеринбург, Свердловская обл., Россия',
    lon: 60.6057,
    lat: 56.8389,
    popularity: 8.0,
  },
  {
    nameRu: 'Новосибирск',
    aliases: 'Novosibirsk',
    type: 'city',
    countryCode: 'RU',
    displayName: 'Новосибирск, Россия',
    lon: 82.9346,
    lat: 54.9884,
    popularity: 7.5,
  },
  {
    nameRu: 'Нижний Новгород',
    aliases: 'Nizhny Novgorod,Нижний',
    type: 'city',
    countryCode: 'RU',
    displayName: 'Нижний Новгород, Россия',
    lon: 44.002,
    lat: 56.3287,
    popularity: 7.5,
  },
  {
    nameRu: 'Краснодар',
    aliases: 'Krasnodar',
    type: 'city',
    countryCode: 'RU',
    displayName: 'Краснодар, Россия',
    lon: 38.9769,
    lat: 45.0355,
    popularity: 7.0,
  },
  {
    nameRu: 'Калининград',
    aliases: 'Kaliningrad,Königsberg',
    type: 'city',
    countryCode: 'RU',
    displayName: 'Калининград, Россия',
    lon: 20.5022,
    lat: 54.7104,
    popularity: 7.5,
  },
  {
    nameRu: 'Уфа',
    aliases: 'Ufa',
    type: 'city',
    countryCode: 'RU',
    displayName: 'Уфа, Башкортостан, Россия',
    lon: 55.9721,
    lat: 54.7388,
    popularity: 6.5,
  },
  {
    nameRu: 'Ростов-на-Дону',
    aliases: 'Rostov-on-Don,Ростов',
    type: 'city',
    countryCode: 'RU',
    displayName: 'Ростов-на-Дону, Россия',
    lon: 39.7015,
    lat: 47.2357,
    popularity: 7.0,
  },
  {
    nameRu: 'Самара',
    aliases: 'Samara',
    type: 'city',
    countryCode: 'RU',
    displayName: 'Самара, Россия',
    lon: 50.1606,
    lat: 53.1959,
    popularity: 6.5,
  },
  {
    nameRu: 'Омск',
    aliases: 'Omsk',
    type: 'city',
    countryCode: 'RU',
    displayName: 'Омск, Россия',
    lon: 73.3686,
    lat: 54.9914,
    popularity: 6.0,
  },
  {
    nameRu: 'Красноярск',
    aliases: 'Krasnoyarsk',
    type: 'city',
    countryCode: 'RU',
    displayName: 'Красноярск, Россия',
    lon: 92.8932,
    lat: 56.0097,
    popularity: 6.5,
  },
  {
    nameRu: 'Воронеж',
    aliases: 'Voronezh',
    type: 'city',
    countryCode: 'RU',
    displayName: 'Воронеж, Россия',
    lon: 39.2006,
    lat: 51.6755,
    popularity: 6.0,
  },
  {
    nameRu: 'Пермь',
    aliases: 'Perm',
    type: 'city',
    countryCode: 'RU',
    displayName: 'Пермь, Россия',
    lon: 56.2291,
    lat: 58.0105,
    popularity: 6.0,
  },
  {
    nameRu: 'Волгоград',
    aliases: 'Volgograd,Сталинград',
    type: 'city',
    countryCode: 'RU',
    displayName: 'Волгоград, Россия',
    lon: 44.5133,
    lat: 48.708,
    popularity: 6.0,
  },
  {
    nameRu: 'Тюмень',
    aliases: 'Tyumen',
    type: 'city',
    countryCode: 'RU',
    displayName: 'Тюмень, Россия',
    lon: 68.9585,
    lat: 57.1522,
    popularity: 6.0,
  },
  {
    nameRu: 'Иркутск',
    aliases: 'Irkutsk',
    type: 'city',
    countryCode: 'RU',
    displayName: 'Иркутск, Россия',
    lon: 104.2964,
    lat: 52.2978,
    popularity: 6.5,
  },
  {
    nameRu: 'Владивосток',
    aliases: 'Vladivostok',
    type: 'city',
    countryCode: 'RU',
    displayName: 'Владивосток, Приморский край, Россия',
    lon: 131.8735,
    lat: 43.1332,
    popularity: 7.0,
  },
  {
    nameRu: 'Хабаровск',
    aliases: 'Khabarovsk',
    type: 'city',
    countryCode: 'RU',
    displayName: 'Хабаровск, Россия',
    lon: 135.0711,
    lat: 48.4827,
    popularity: 6.0,
  },
  {
    nameRu: 'Мурманск',
    aliases: 'Murmansk',
    type: 'city',
    countryCode: 'RU',
    displayName: 'Мурманск, Россия',
    lon: 33.0856,
    lat: 68.9585,
    popularity: 6.5,
  },
  {
    nameRu: 'Якутск',
    aliases: 'Yakutsk',
    type: 'city',
    countryCode: 'RU',
    displayName: 'Якутск, Якутия, Россия',
    lon: 129.7331,
    lat: 62.0397,
    popularity: 5.5,
  },
  {
    nameRu: 'Новороссийск',
    aliases: 'Novorossiysk',
    type: 'city',
    countryCode: 'RU',
    displayName: 'Новороссийск, Краснодарский край, Россия',
    lon: 37.7685,
    lat: 44.7239,
    popularity: 5.5,
  },
  {
    nameRu: 'Ставрополь',
    aliases: 'Stavropol',
    type: 'city',
    countryCode: 'RU',
    displayName: 'Ставрополь, Россия',
    lon: 41.9734,
    lat: 45.0428,
    popularity: 5.5,
  },
  {
    nameRu: 'Минеральные Воды',
    aliases: 'Mineralnye Vody,МинВоды',
    type: 'city',
    countryCode: 'RU',
    displayName: 'Минеральные Воды, Ставропольский край, Россия',
    lon: 43.139,
    lat: 44.2118,
    popularity: 6.0,
  },
  {
    nameRu: 'Кисловодск',
    aliases: 'Kislovodsk',
    type: 'resort',
    countryCode: 'RU',
    displayName: 'Кисловодск, Ставропольский край, Россия',
    lon: 42.7186,
    lat: 43.9067,
    popularity: 6.5,
  },
  {
    nameRu: 'Пятигорск',
    aliases: 'Pyatigorsk',
    type: 'city',
    countryCode: 'RU',
    displayName: 'Пятигорск, Ставропольский край, Россия',
    lon: 43.0605,
    lat: 44.0469,
    popularity: 6.0,
  },
  {
    nameRu: 'Геленджик',
    aliases: 'Gelendzhik',
    type: 'resort',
    countryCode: 'RU',
    displayName: 'Геленджик, Краснодарский край, Россия',
    lon: 38.0764,
    lat: 44.5615,
    popularity: 7.0,
  },
  {
    nameRu: 'Анапа',
    aliases: 'Anapa',
    type: 'resort',
    countryCode: 'RU',
    displayName: 'Анапа, Краснодарский край, Россия',
    lon: 37.3159,
    lat: 44.8952,
    popularity: 7.0,
  },
  {
    nameRu: 'Темрюк',
    aliases: 'Temryuk',
    type: 'city',
    countryCode: 'RU',
    displayName: 'Темрюк, Краснодарский край, Россия',
    lon: 37.3757,
    lat: 45.2741,
    popularity: 5.0,
  },
  {
    nameRu: 'Абрау-Дюрсо',
    aliases: 'Abrau-Dyurso',
    type: 'resort',
    countryCode: 'RU',
    displayName: 'Абрау-Дюрсо, Краснодарский край, Россия',
    lon: 37.5478,
    lat: 44.7005,
    popularity: 5.5,
  },
  {
    nameRu: 'Байкал',
    aliases: 'Baikal,озеро Байкал',
    type: 'region',
    countryCode: 'RU',
    displayName: 'Озеро Байкал, Иркутская область, Россия',
    lon: 107.6833,
    lat: 53.5,
    popularity: 8.0,
  },
  {
    nameRu: 'Листвянка',
    aliases: 'Listvyanka',
    type: 'resort',
    countryCode: 'RU',
    displayName: 'Листвянка, Иркутская область, Россия',
    lon: 104.8553,
    lat: 51.85,
    popularity: 6.5,
  },
  {
    nameRu: 'Суздаль',
    aliases: 'Suzdal',
    type: 'city',
    countryCode: 'RU',
    displayName: 'Суздаль, Владимирская область, Россия',
    lon: 40.4467,
    lat: 56.4286,
    popularity: 7.0,
  },
  {
    nameRu: 'Владимир',
    aliases: 'Vladimir',
    type: 'city',
    countryCode: 'RU',
    displayName: 'Владимир, Россия',
    lon: 40.4069,
    lat: 56.129,
    popularity: 6.5,
  },
  {
    nameRu: 'Великий Новгород',
    aliases: 'Veliky Novgorod,Novgorod',
    type: 'city',
    countryCode: 'RU',
    displayName: 'Великий Новгород, Россия',
    lon: 31.2717,
    lat: 58.522,
    popularity: 6.5,
  },
  {
    nameRu: 'Псков',
    aliases: 'Pskov',
    type: 'city',
    countryCode: 'RU',
    displayName: 'Псков, Россия',
    lon: 28.3314,
    lat: 57.8136,
    popularity: 6.0,
  },
  {
    nameRu: 'Выборг',
    aliases: 'Vyborg',
    type: 'city',
    countryCode: 'RU',
    displayName: 'Выборг, Ленинградская область, Россия',
    lon: 28.7528,
    lat: 60.7076,
    popularity: 6.5,
  },
  {
    nameRu: 'Архангельск',
    aliases: 'Arkhangelsk',
    type: 'city',
    countryCode: 'RU',
    displayName: 'Архангельск, Россия',
    lon: 40.5433,
    lat: 64.5401,
    popularity: 5.5,
  },
  {
    nameRu: 'Карелия',
    aliases: 'Karelia',
    type: 'region',
    countryCode: 'RU',
    displayName: 'Республика Карелия, Россия',
    lon: 32.5,
    lat: 62.5,
    popularity: 7.5,
  },
  {
    nameRu: 'Петрозаводск',
    aliases: 'Petrozavodsk',
    type: 'city',
    countryCode: 'RU',
    displayName: 'Петрозаводск, Карелия, Россия',
    lon: 34.3636,
    lat: 61.7891,
    popularity: 6.5,
  },
  {
    nameRu: 'Кижи',
    aliases: 'Kizhi',
    type: 'region',
    countryCode: 'RU',
    displayName: 'Кижи, Карелия, Россия',
    lon: 33.0938,
    lat: 62.0681,
    popularity: 7.0,
  },
  {
    nameRu: 'Алтай',
    aliases: 'Altai,Горный Алтай',
    type: 'region',
    countryCode: 'RU',
    displayName: 'Горный Алтай, Россия',
    lon: 86.5,
    lat: 50.5,
    popularity: 8.0,
  },
  {
    nameRu: 'Горно-Алтайск',
    aliases: 'Gorno-Altaysk',
    type: 'city',
    countryCode: 'RU',
    displayName: 'Горно-Алтайск, Алтай, Россия',
    lon: 85.9603,
    lat: 51.9581,
    popularity: 6.0,
  },
  {
    nameRu: 'Белокуриха',
    aliases: 'Belokurikha',
    type: 'resort',
    countryCode: 'RU',
    displayName: 'Белокуриха, Алтайский край, Россия',
    lon: 84.9911,
    lat: 51.9957,
    popularity: 6.0,
  },
  {
    nameRu: 'Камчатка',
    aliases: 'Kamchatka',
    type: 'region',
    countryCode: 'RU',
    displayName: 'Камчатский край, Россия',
    lon: 160.0,
    lat: 54.0,
    popularity: 7.5,
  },
  {
    nameRu: 'Петропавловск-Камчатский',
    aliases: 'Petropavlovsk-Kamchatsky',
    type: 'city',
    countryCode: 'RU',
    displayName: 'Петропавловск-Камчатский, Россия',
    lon: 158.65,
    lat: 53.0167,
    popularity: 6.0,
  },
  {
    nameRu: 'Сахалин',
    aliases: 'Sakhalin',
    type: 'region',
    countryCode: 'RU',
    displayName: 'Остров Сахалин, Россия',
    lon: 143.0,
    lat: 51.0,
    popularity: 6.0,
  },
  {
    nameRu: 'Южно-Сахалинск',
    aliases: 'Yuzhno-Sakhalinsk',
    type: 'city',
    countryCode: 'RU',
    displayName: 'Южно-Сахалинск, Сахалин, Россия',
    lon: 142.7353,
    lat: 46.9588,
    popularity: 5.5,
  },
  {
    nameRu: 'Кавказ',
    aliases: 'Caucasus',
    type: 'region',
    countryCode: 'RU',
    displayName: 'Северный Кавказ, Россия',
    lon: 43.0,
    lat: 43.0,
    popularity: 6.0,
  },
  {
    nameRu: 'Домбай',
    aliases: 'Dombai',
    type: 'resort',
    countryCode: 'RU',
    displayName: 'Домбай, Карачаево-Черкесия, Россия',
    lon: 41.7297,
    lat: 43.2892,
    popularity: 7.0,
  },
  {
    nameRu: 'Эльбрус',
    aliases: 'Elbrus,Приэльбрусье',
    type: 'resort',
    countryCode: 'RU',
    displayName: 'Приэльбрусье, Кабардино-Балкария, Россия',
    lon: 42.4578,
    lat: 43.3553,
    popularity: 7.5,
  },
  {
    nameRu: 'Архыз',
    aliases: 'Arkhyz',
    type: 'resort',
    countryCode: 'RU',
    displayName: 'Архыз, Карачаево-Черкесия, Россия',
    lon: 41.2833,
    lat: 43.55,
    popularity: 6.5,
  },
  {
    nameRu: 'Грозный',
    aliases: 'Grozny',
    type: 'city',
    countryCode: 'RU',
    displayName: 'Грозный, Чечня, Россия',
    lon: 45.69,
    lat: 43.318,
    popularity: 6.0,
  },
  {
    nameRu: 'Махачкала',
    aliases: 'Makhachkala',
    type: 'city',
    countryCode: 'RU',
    displayName: 'Махачкала, Дагестан, Россия',
    lon: 47.5042,
    lat: 42.9849,
    popularity: 6.5,
  },
  {
    nameRu: 'Дербент',
    aliases: 'Derbent',
    type: 'city',
    countryCode: 'RU',
    displayName: 'Дербент, Дагестан, Россия',
    lon: 48.2895,
    lat: 42.0597,
    popularity: 7.0,
  },
  {
    nameRu: 'Крым',
    aliases: 'Crimea',
    type: 'region',
    countryCode: 'RU',
    displayName: 'Республика Крым, Россия',
    lon: 34.0,
    lat: 45.0,
    popularity: 7.5,
  },
  {
    nameRu: 'Симферополь',
    aliases: 'Simferopol',
    type: 'city',
    countryCode: 'RU',
    displayName: 'Симферополь, Крым, Россия',
    lon: 34.101,
    lat: 44.9527,
    popularity: 6.5,
  },
  {
    nameRu: 'Ялта',
    aliases: 'Yalta',
    type: 'resort',
    countryCode: 'RU',
    displayName: 'Ялта, Крым, Россия',
    lon: 34.1553,
    lat: 44.495,
    popularity: 7.5,
  },
  {
    nameRu: 'Севастополь',
    aliases: 'Sevastopol',
    type: 'city',
    countryCode: 'RU',
    displayName: 'Севастополь, Крым, Россия',
    lon: 33.5254,
    lat: 44.6054,
    popularity: 7.0,
  },
  {
    nameRu: 'Феодосия',
    aliases: 'Feodosia',
    type: 'resort',
    countryCode: 'RU',
    displayName: 'Феодосия, Крым, Россия',
    lon: 35.383,
    lat: 45.031,
    popularity: 6.5,
  },
  {
    nameRu: 'Евпатория',
    aliases: 'Yevpatoria',
    type: 'resort',
    countryCode: 'RU',
    displayName: 'Евпатория, Крым, Россия',
    lon: 33.3773,
    lat: 45.2021,
    popularity: 6.5,
  },
  {
    nameRu: 'Алушта',
    aliases: 'Alushta',
    type: 'resort',
    countryCode: 'RU',
    displayName: 'Алушта, Крым, Россия',
    lon: 34.4111,
    lat: 44.6757,
    popularity: 6.5,
  },

  // ─── АЭРОПОРТЫ РОССИИ ─────────────────────────────────────────────────────
  {
    nameRu: 'Шереметьево',
    aliases: 'SVO,Sheremetyevo',
    type: 'airport',
    countryCode: 'RU',
    displayName: 'Аэропорт Шереметьево (SVO), Москва, Россия',
    lon: 37.4146,
    lat: 55.9736,
    popularity: 9.0,
  },
  {
    nameRu: 'Домодедово',
    aliases: 'DME,Domodedovo',
    type: 'airport',
    countryCode: 'RU',
    displayName: 'Аэропорт Домодедово (DME), Москва, Россия',
    lon: 37.9063,
    lat: 55.4103,
    popularity: 8.5,
  },
  {
    nameRu: 'Внуково',
    aliases: 'VKO,Vnukovo',
    type: 'airport',
    countryCode: 'RU',
    displayName: 'Аэропорт Внуково (VKO), Москва, Россия',
    lon: 37.2615,
    lat: 55.5915,
    popularity: 8.0,
  },
  {
    nameRu: 'Пулково',
    aliases: 'LED,Pulkovo',
    type: 'airport',
    countryCode: 'RU',
    displayName: 'Аэропорт Пулково (LED), Санкт-Петербург, Россия',
    lon: 30.2627,
    lat: 59.8003,
    popularity: 8.5,
  },
  {
    nameRu: 'Адлер',
    aliases: 'AER,Адлер',
    type: 'airport',
    countryCode: 'RU',
    displayName: 'Аэропорт Сочи-Адлер (AER), Сочи, Россия',
    lon: 39.9566,
    lat: 43.449,
    popularity: 8.0,
  },

  // ─── ТУРЦИЯ ───────────────────────────────────────────────────────────────
  {
    nameRu: 'Анталья',
    aliases: 'Antalya,AYT',
    type: 'city',
    countryCode: 'TR',
    displayName: 'Анталья, Турция',
    lon: 30.7133,
    lat: 36.8969,
    popularity: 9.5,
  },
  {
    nameRu: 'Стамбул',
    aliases: 'Istanbul,IST,Константинополь',
    type: 'city',
    countryCode: 'TR',
    displayName: 'Стамбул, Турция',
    lon: 28.9784,
    lat: 41.0082,
    popularity: 9.5,
  },
  {
    nameRu: 'Аланья',
    aliases: 'Alanya',
    type: 'resort',
    countryCode: 'TR',
    displayName: 'Аланья, Турция',
    lon: 32.0087,
    lat: 36.544,
    popularity: 9.0,
  },
  {
    nameRu: 'Кемер',
    aliases: 'Kemer',
    type: 'resort',
    countryCode: 'TR',
    displayName: 'Кемер, Анталья, Турция',
    lon: 30.5578,
    lat: 36.5978,
    popularity: 8.5,
  },
  {
    nameRu: 'Белек',
    aliases: 'Belek',
    type: 'resort',
    countryCode: 'TR',
    displayName: 'Белек, Анталья, Турция',
    lon: 31.0664,
    lat: 36.8528,
    popularity: 8.5,
  },
  {
    nameRu: 'Сиде',
    aliases: 'Side',
    type: 'resort',
    countryCode: 'TR',
    displayName: 'Сиде, Анталья, Турция',
    lon: 31.3882,
    lat: 36.7675,
    popularity: 8.5,
  },
  {
    nameRu: 'Бодрум',
    aliases: 'Bodrum',
    type: 'resort',
    countryCode: 'TR',
    displayName: 'Бодрум, Мугла, Турция',
    lon: 27.4242,
    lat: 37.0344,
    popularity: 8.0,
  },
  {
    nameRu: 'Мармарис',
    aliases: 'Marmaris',
    type: 'resort',
    countryCode: 'TR',
    displayName: 'Мармарис, Мугла, Турция',
    lon: 28.2722,
    lat: 36.8553,
    popularity: 8.0,
  },
  {
    nameRu: 'Фетхие',
    aliases: 'Fethiye',
    type: 'resort',
    countryCode: 'TR',
    displayName: 'Фетхие, Мугла, Турция',
    lon: 29.1189,
    lat: 36.6558,
    popularity: 7.5,
  },
  {
    nameRu: 'Каппадокия',
    aliases: 'Cappadocia,Каппадокия',
    type: 'region',
    countryCode: 'TR',
    displayName: 'Каппадокия, Невшехир, Турция',
    lon: 34.8293,
    lat: 38.6431,
    popularity: 8.5,
  },
  {
    nameRu: 'Невшехир',
    aliases: 'Nevsehir,NAV',
    type: 'city',
    countryCode: 'TR',
    displayName: 'Невшехир (Каппадокия), Турция',
    lon: 34.7242,
    lat: 38.6246,
    popularity: 7.5,
  },
  {
    nameRu: 'Измир',
    aliases: 'Izmir,Smyrna',
    type: 'city',
    countryCode: 'TR',
    displayName: 'Измир, Турция',
    lon: 27.1428,
    lat: 38.4237,
    popularity: 7.5,
  },
  {
    nameRu: 'Анкара',
    aliases: 'Ankara',
    type: 'city',
    countryCode: 'TR',
    displayName: 'Анкара, Турция',
    lon: 32.8597,
    lat: 39.9334,
    popularity: 7.0,
  },
  {
    nameRu: 'Трабзон',
    aliases: 'Trabzon',
    type: 'city',
    countryCode: 'TR',
    displayName: 'Трабзон, Турция',
    lon: 39.7267,
    lat: 41.0015,
    popularity: 6.5,
  },
  {
    nameRu: 'Дидим',
    aliases: 'Didim,Didyma',
    type: 'resort',
    countryCode: 'TR',
    displayName: 'Дидим, Айдын, Турция',
    lon: 27.2683,
    lat: 37.3789,
    popularity: 7.0,
  },
  {
    nameRu: 'Кушадасы',
    aliases: 'Kusadasi',
    type: 'resort',
    countryCode: 'TR',
    displayName: 'Кушадасы, Айдын, Турция',
    lon: 27.262,
    lat: 37.856,
    popularity: 7.0,
  },

  // ─── ОАЭ ─────────────────────────────────────────────────────────────────
  {
    nameRu: 'Дубай',
    aliases: 'Dubai,DXB',
    type: 'city',
    countryCode: 'AE',
    displayName: 'Дубай, ОАЭ',
    lon: 55.2708,
    lat: 25.2048,
    popularity: 9.5,
  },
  {
    nameRu: 'Абу-Даби',
    aliases: 'Abu Dhabi,AUH,Абу Даби',
    type: 'city',
    countryCode: 'AE',
    displayName: 'Абу-Даби, ОАЭ',
    lon: 54.3773,
    lat: 24.4539,
    popularity: 8.5,
  },
  {
    nameRu: 'Шарджа',
    aliases: 'Sharjah,SHJ',
    type: 'city',
    countryCode: 'AE',
    displayName: 'Шарджа, ОАЭ',
    lon: 55.382,
    lat: 25.3462,
    popularity: 7.5,
  },
  {
    nameRu: 'Рас-эль-Хайма',
    aliases: 'Ras al Khaimah,RAK,РАК',
    type: 'city',
    countryCode: 'AE',
    displayName: 'Рас-эль-Хайма, ОАЭ',
    lon: 55.9438,
    lat: 25.7895,
    popularity: 7.5,
  },
  {
    nameRu: 'Фуджейра',
    aliases: 'Fujairah',
    type: 'city',
    countryCode: 'AE',
    displayName: 'Фуджейра, ОАЭ',
    lon: 56.3411,
    lat: 25.1288,
    popularity: 6.5,
  },

  // ─── ЕГИПЕТ ───────────────────────────────────────────────────────────────
  {
    nameRu: 'Шарм-эль-Шейх',
    aliases: 'Sharm el-Sheikh,SSH,Шарм',
    type: 'resort',
    countryCode: 'EG',
    displayName: 'Шарм-эль-Шейх, Египет',
    lon: 34.33,
    lat: 27.9158,
    popularity: 9.0,
  },
  {
    nameRu: 'Хургада',
    aliases: 'Hurghada,HRG',
    type: 'resort',
    countryCode: 'EG',
    displayName: 'Хургада, Египет',
    lon: 33.8116,
    lat: 27.2574,
    popularity: 9.0,
  },
  {
    nameRu: 'Каир',
    aliases: 'Cairo,CAI',
    type: 'city',
    countryCode: 'EG',
    displayName: 'Каир, Египет',
    lon: 31.2357,
    lat: 30.0444,
    popularity: 8.0,
  },
  {
    nameRu: 'Луксор',
    aliases: 'Luxor,LXR',
    type: 'city',
    countryCode: 'EG',
    displayName: 'Луксор, Египет',
    lon: 32.6396,
    lat: 25.6872,
    popularity: 7.5,
  },
  {
    nameRu: 'Дахаб',
    aliases: 'Dahab',
    type: 'resort',
    countryCode: 'EG',
    displayName: 'Дахаб, Синай, Египет',
    lon: 34.5133,
    lat: 28.4887,
    popularity: 7.0,
  },
  {
    nameRu: 'Марса Алам',
    aliases: 'Marsa Alam,RMF',
    type: 'resort',
    countryCode: 'EG',
    displayName: 'Марса Алам, Египет',
    lon: 34.8939,
    lat: 25.0653,
    popularity: 7.0,
  },

  // ─── ТАИЛАНД ─────────────────────────────────────────────────────────────
  {
    nameRu: 'Пхукет',
    aliases: 'Phuket,HKT',
    type: 'island',
    countryCode: 'TH',
    displayName: 'Пхукет, Таиланд',
    lon: 98.3923,
    lat: 7.8804,
    popularity: 9.5,
  },
  {
    nameRu: 'Бангкок',
    aliases: 'Bangkok,BKK,Крунг Тхеп',
    type: 'city',
    countryCode: 'TH',
    displayName: 'Бангкок, Таиланд',
    lon: 100.5018,
    lat: 13.7563,
    popularity: 9.0,
  },
  {
    nameRu: 'Паттайя',
    aliases: 'Pattaya',
    type: 'resort',
    countryCode: 'TH',
    displayName: 'Паттайя, Чонбури, Таиланд',
    lon: 100.8803,
    lat: 12.9236,
    popularity: 9.0,
  },
  {
    nameRu: 'Самуи',
    aliases: 'Koh Samui,USM,Ко Самуи',
    type: 'island',
    countryCode: 'TH',
    displayName: 'Самуи, Сураттхани, Таиланд',
    lon: 100.0627,
    lat: 9.5018,
    popularity: 8.5,
  },
  {
    nameRu: 'Краби',
    aliases: 'Krabi,KBV',
    type: 'resort',
    countryCode: 'TH',
    displayName: 'Краби, Таиланд',
    lon: 98.9062,
    lat: 8.0863,
    popularity: 8.5,
  },
  {
    nameRu: 'Чиангмай',
    aliases: 'Chiang Mai,CNX',
    type: 'city',
    countryCode: 'TH',
    displayName: 'Чиангмай, Таиланд',
    lon: 98.9817,
    lat: 18.7904,
    popularity: 8.0,
  },
  {
    nameRu: 'Ко Панган',
    aliases: 'Koh Phangan,Панган',
    type: 'island',
    countryCode: 'TH',
    displayName: 'Ко Панган, Таиланд',
    lon: 100.0588,
    lat: 9.738,
    popularity: 7.5,
  },
  {
    nameRu: 'Ко Тао',
    aliases: 'Koh Tao',
    type: 'island',
    countryCode: 'TH',
    displayName: 'Ко Тао, Таиланд',
    lon: 99.8406,
    lat: 10.0956,
    popularity: 7.0,
  },
  {
    nameRu: 'Пхи-Пхи',
    aliases: 'Phi Phi,Ko Phi Phi',
    type: 'island',
    countryCode: 'TH',
    displayName: 'Острова Пхи-Пхи, Краби, Таиланд',
    lon: 98.7784,
    lat: 7.7407,
    popularity: 8.0,
  },

  // ─── ВЬЕТНАМ ─────────────────────────────────────────────────────────────
  {
    nameRu: 'Нячанг',
    aliases: 'Nha Trang,CXR',
    type: 'resort',
    countryCode: 'VN',
    displayName: 'Нячанг, Вьетнам',
    lon: 109.1967,
    lat: 12.2388,
    popularity: 8.5,
  },
  {
    nameRu: 'Фукуок',
    aliases: 'Phu Quoc,PQC,Фу Куок',
    type: 'island',
    countryCode: 'VN',
    displayName: 'Фукуок, Вьетнам',
    lon: 103.984,
    lat: 10.2899,
    popularity: 8.5,
  },
  {
    nameRu: 'Дананг',
    aliases: 'Da Nang,DAD',
    type: 'city',
    countryCode: 'VN',
    displayName: 'Дананг, Вьетнам',
    lon: 108.2022,
    lat: 16.0544,
    popularity: 8.0,
  },
  {
    nameRu: 'Ханой',
    aliases: 'Hanoi,HAN',
    type: 'city',
    countryCode: 'VN',
    displayName: 'Ханой, Вьетнам',
    lon: 105.8342,
    lat: 21.0285,
    popularity: 8.0,
  },
  {
    nameRu: 'Хошимин',
    aliases: 'Ho Chi Minh City,SGN,Сайгон',
    type: 'city',
    countryCode: 'VN',
    displayName: 'Хошимин, Вьетнам',
    lon: 106.6297,
    lat: 10.8231,
    popularity: 8.0,
  },
  {
    nameRu: 'Хойан',
    aliases: 'Hoi An',
    type: 'city',
    countryCode: 'VN',
    displayName: 'Хойан, Вьетнам',
    lon: 108.338,
    lat: 15.88,
    popularity: 7.5,
  },
  {
    nameRu: 'Хюэ',
    aliases: 'Hue',
    type: 'city',
    countryCode: 'VN',
    displayName: 'Хюэ, Вьетнам',
    lon: 107.5905,
    lat: 16.4637,
    popularity: 7.0,
  },
  {
    nameRu: 'Муйне',
    aliases: 'Mui Ne,Муй Не',
    type: 'resort',
    countryCode: 'VN',
    displayName: 'Муйне, Вьетнам',
    lon: 108.2897,
    lat: 10.9333,
    popularity: 7.5,
  },

  // ─── ГРУЗИЯ ───────────────────────────────────────────────────────────────
  {
    nameRu: 'Тбилиси',
    aliases: 'Tbilisi,TBS',
    type: 'city',
    countryCode: 'GE',
    displayName: 'Тбилиси, Грузия',
    lon: 44.7975,
    lat: 41.6941,
    popularity: 9.0,
  },
  {
    nameRu: 'Батуми',
    aliases: 'Batumi,BUS',
    type: 'city',
    countryCode: 'GE',
    displayName: 'Батуми, Аджария, Грузия',
    lon: 41.6427,
    lat: 41.6417,
    popularity: 8.5,
  },
  {
    nameRu: 'Кутаиси',
    aliases: 'Kutaisi,KUT',
    type: 'city',
    countryCode: 'GE',
    displayName: 'Кутаиси, Грузия',
    lon: 42.7009,
    lat: 42.2675,
    popularity: 7.5,
  },
  {
    nameRu: 'Сигнахи',
    aliases: 'Signagi,Sighnaghi',
    type: 'city',
    countryCode: 'GE',
    displayName: 'Сигнахи, Кахетия, Грузия',
    lon: 45.9232,
    lat: 41.6088,
    popularity: 7.0,
  },
  {
    nameRu: 'Мцхета',
    aliases: 'Mtskheta',
    type: 'city',
    countryCode: 'GE',
    displayName: 'Мцхета, Грузия',
    lon: 44.7196,
    lat: 41.8453,
    popularity: 7.0,
  },
  {
    nameRu: 'Казбеги',
    aliases: 'Kazbegi,Степанцминда',
    type: 'resort',
    countryCode: 'GE',
    displayName: 'Казбеги (Степанцминда), Грузия',
    lon: 44.6506,
    lat: 42.6597,
    popularity: 8.0,
  },
  {
    nameRu: 'Местиа',
    aliases: 'Mestia',
    type: 'resort',
    countryCode: 'GE',
    displayName: 'Местиа, Сванетия, Грузия',
    lon: 46.0,
    lat: 43.0436,
    popularity: 7.5,
  },

  // ─── АБХАЗИЯ ─────────────────────────────────────────────────────────────
  {
    nameRu: 'Сухум',
    aliases: 'Sukhum,Сухуми',
    type: 'city',
    countryCode: 'AB',
    displayName: 'Сухум, Абхазия',
    lon: 41.015,
    lat: 43.0015,
    popularity: 7.0,
  },
  {
    nameRu: 'Гагра',
    aliases: 'Gagra',
    type: 'resort',
    countryCode: 'AB',
    displayName: 'Гагра, Абхазия',
    lon: 40.2651,
    lat: 43.2783,
    popularity: 7.5,
  },
  {
    nameRu: 'Пицунда',
    aliases: 'Pitsunda',
    type: 'resort',
    countryCode: 'AB',
    displayName: 'Пицунда, Абхазия',
    lon: 41.1828,
    lat: 43.1574,
    popularity: 7.0,
  },
  {
    nameRu: 'Новый Афон',
    aliases: 'Novy Afon,Ново-Афонский монастырь',
    type: 'resort',
    countryCode: 'AB',
    displayName: 'Новый Афон, Абхазия',
    lon: 40.815,
    lat: 43.0892,
    popularity: 7.0,
  },

  // ─── АРМЕНИЯ ─────────────────────────────────────────────────────────────
  {
    nameRu: 'Ереван',
    aliases: 'Yerevan,EVN',
    type: 'city',
    countryCode: 'AM',
    displayName: 'Ереван, Армения',
    lon: 44.5136,
    lat: 40.1872,
    popularity: 8.5,
  },
  {
    nameRu: 'Гюмри',
    aliases: 'Gyumri',
    type: 'city',
    countryCode: 'AM',
    displayName: 'Гюмри, Армения',
    lon: 43.8484,
    lat: 40.7942,
    popularity: 6.5,
  },
  {
    nameRu: 'Дилижан',
    aliases: 'Dilijan',
    type: 'resort',
    countryCode: 'AM',
    displayName: 'Дилижан, Армения',
    lon: 44.8608,
    lat: 40.7424,
    popularity: 7.0,
  },
  {
    nameRu: 'Цахкадзор',
    aliases: 'Tsakhkadzor',
    type: 'resort',
    countryCode: 'AM',
    displayName: 'Цахкадзор, Армения',
    lon: 44.7544,
    lat: 40.5564,
    popularity: 7.0,
  },

  // ─── АЗЕРБАЙДЖАН ─────────────────────────────────────────────────────────
  {
    nameRu: 'Баку',
    aliases: 'Baku,GYD',
    type: 'city',
    countryCode: 'AZ',
    displayName: 'Баку, Азербайджан',
    lon: 49.8671,
    lat: 40.4093,
    popularity: 8.5,
  },
  {
    nameRu: 'Шеки',
    aliases: 'Sheki,Шэки',
    type: 'city',
    countryCode: 'AZ',
    displayName: 'Шеки, Азербайджан',
    lon: 47.1706,
    lat: 41.1988,
    popularity: 6.5,
  },
  {
    nameRu: 'Габала',
    aliases: 'Gabala,Qabala',
    type: 'resort',
    countryCode: 'AZ',
    displayName: 'Габала, Азербайджан',
    lon: 47.8717,
    lat: 40.9988,
    popularity: 6.5,
  },

  // ─── КАЗАХСТАН ───────────────────────────────────────────────────────────
  {
    nameRu: 'Алматы',
    aliases: 'Almaty,ALA,Алма-Ата',
    type: 'city',
    countryCode: 'KZ',
    displayName: 'Алматы, Казахстан',
    lon: 76.8512,
    lat: 43.222,
    popularity: 8.5,
  },
  {
    nameRu: 'Астана',
    aliases: 'Astana,NQZ,Нур-Султан',
    type: 'city',
    countryCode: 'KZ',
    displayName: 'Астана, Казахстан',
    lon: 71.4306,
    lat: 51.1801,
    popularity: 7.5,
  },
  {
    nameRu: 'Шымкент',
    aliases: 'Shymkent',
    type: 'city',
    countryCode: 'KZ',
    displayName: 'Шымкент, Казахстан',
    lon: 69.59,
    lat: 42.3,
    popularity: 6.5,
  },

  // ─── УЗБЕКИСТАН ──────────────────────────────────────────────────────────
  {
    nameRu: 'Ташкент',
    aliases: 'Tashkent,TAS',
    type: 'city',
    countryCode: 'UZ',
    displayName: 'Ташкент, Узбекистан',
    lon: 69.2401,
    lat: 41.2995,
    popularity: 8.0,
  },
  {
    nameRu: 'Самарканд',
    aliases: 'Samarkand,SKD',
    type: 'city',
    countryCode: 'UZ',
    displayName: 'Самарканд, Узбекистан',
    lon: 66.9597,
    lat: 39.6542,
    popularity: 8.5,
  },
  {
    nameRu: 'Бухара',
    aliases: 'Bukhara,BHK',
    type: 'city',
    countryCode: 'UZ',
    displayName: 'Бухара, Узбекистан',
    lon: 64.4231,
    lat: 39.7747,
    popularity: 8.0,
  },
  {
    nameRu: 'Хива',
    aliases: 'Khiva,Xiva',
    type: 'city',
    countryCode: 'UZ',
    displayName: 'Хива, Узбекистан',
    lon: 60.3628,
    lat: 41.3775,
    popularity: 7.5,
  },

  // ─── БЕЛАРУСЬ ────────────────────────────────────────────────────────────
  {
    nameRu: 'Минск',
    aliases: 'Minsk,MSQ',
    type: 'city',
    countryCode: 'BY',
    displayName: 'Минск, Беларусь',
    lon: 27.5615,
    lat: 53.9045,
    popularity: 8.0,
  },
  {
    nameRu: 'Брест',
    aliases: 'Brest',
    type: 'city',
    countryCode: 'BY',
    displayName: 'Брест, Беларусь',
    lon: 23.6884,
    lat: 52.0976,
    popularity: 7.0,
  },
  {
    nameRu: 'Гродно',
    aliases: 'Grodno,Hrodna',
    type: 'city',
    countryCode: 'BY',
    displayName: 'Гродно, Беларусь',
    lon: 23.8344,
    lat: 53.6884,
    popularity: 6.5,
  },
  {
    nameRu: 'Несвиж',
    aliases: 'Nesvizh',
    type: 'city',
    countryCode: 'BY',
    displayName: 'Несвиж, Беларусь',
    lon: 26.688,
    lat: 53.2196,
    popularity: 6.5,
  },

  // ─── КИТАЙ ───────────────────────────────────────────────────────────────
  {
    nameRu: 'Пекин',
    aliases: 'Beijing,PEK,Бейджин',
    type: 'city',
    countryCode: 'CN',
    displayName: 'Пекин, Китай',
    lon: 116.3912,
    lat: 39.9042,
    popularity: 8.5,
  },
  {
    nameRu: 'Шанхай',
    aliases: 'Shanghai,SHA,PVG',
    type: 'city',
    countryCode: 'CN',
    displayName: 'Шанхай, Китай',
    lon: 121.4737,
    lat: 31.2304,
    popularity: 8.5,
  },
  {
    nameRu: 'Хайнань',
    aliases: 'Hainan,HAK',
    type: 'island',
    countryCode: 'CN',
    displayName: 'Хайнань, Китай',
    lon: 109.7453,
    lat: 19.1959,
    popularity: 8.5,
  },
  {
    nameRu: 'Санья',
    aliases: 'Sanya,SYX',
    type: 'resort',
    countryCode: 'CN',
    displayName: 'Санья, Хайнань, Китай',
    lon: 109.5125,
    lat: 18.2528,
    popularity: 8.0,
  },
  {
    nameRu: 'Гуанчжоу',
    aliases: 'Guangzhou,CAN,Kanton',
    type: 'city',
    countryCode: 'CN',
    displayName: 'Гуанчжоу, Китай',
    lon: 113.2644,
    lat: 23.1291,
    popularity: 7.5,
  },

  // ─── ЯПОНИЯ ──────────────────────────────────────────────────────────────
  {
    nameRu: 'Токио',
    aliases: 'Tokyo,TYO,NRT,HND',
    type: 'city',
    countryCode: 'JP',
    displayName: 'Токио, Япония',
    lon: 139.6917,
    lat: 35.6895,
    popularity: 9.0,
  },
  {
    nameRu: 'Осака',
    aliases: 'Osaka,KIX',
    type: 'city',
    countryCode: 'JP',
    displayName: 'Осака, Япония',
    lon: 135.5023,
    lat: 34.6937,
    popularity: 8.5,
  },
  {
    nameRu: 'Киото',
    aliases: 'Kyoto',
    type: 'city',
    countryCode: 'JP',
    displayName: 'Киото, Япония',
    lon: 135.7681,
    lat: 35.0116,
    popularity: 8.5,
  },
  {
    nameRu: 'Саппоро',
    aliases: 'Sapporo,CTS',
    type: 'city',
    countryCode: 'JP',
    displayName: 'Саппоро, Хоккайдо, Япония',
    lon: 141.3469,
    lat: 43.0618,
    popularity: 7.5,
  },

  // ─── ЮЖНАЯ КОРЕЯ ─────────────────────────────────────────────────────────
  {
    nameRu: 'Сеул',
    aliases: 'Seoul,ICN,GMP',
    type: 'city',
    countryCode: 'KR',
    displayName: 'Сеул, Южная Корея',
    lon: 126.978,
    lat: 37.5665,
    popularity: 8.5,
  },
  {
    nameRu: 'Пусан',
    aliases: 'Busan,PUS',
    type: 'city',
    countryCode: 'KR',
    displayName: 'Пусан, Южная Корея',
    lon: 129.0756,
    lat: 35.1796,
    popularity: 7.5,
  },
  {
    nameRu: 'Чеджу',
    aliases: 'Jeju,CJU,Чежу',
    type: 'island',
    countryCode: 'KR',
    displayName: 'Остров Чеджу, Южная Корея',
    lon: 126.5312,
    lat: 33.4996,
    popularity: 7.5,
  },

  // ─── ИНДИЯ ────────────────────────────────────────────────────────────────
  {
    nameRu: 'Гоа',
    aliases: 'Goa,GOI',
    type: 'region',
    countryCode: 'IN',
    displayName: 'Гоа, Индия',
    lon: 74.124,
    lat: 15.2993,
    popularity: 8.5,
  },
  {
    nameRu: 'Дели',
    aliases: 'Delhi,New Delhi,DEL',
    type: 'city',
    countryCode: 'IN',
    displayName: 'Нью-Дели, Индия',
    lon: 77.1025,
    lat: 28.7041,
    popularity: 8.0,
  },
  {
    nameRu: 'Мумбаи',
    aliases: 'Mumbai,Bombay,BOM',
    type: 'city',
    countryCode: 'IN',
    displayName: 'Мумбаи, Индия',
    lon: 72.8777,
    lat: 19.076,
    popularity: 7.5,
  },
  {
    nameRu: 'Агра',
    aliases: 'Agra,AGR',
    type: 'city',
    countryCode: 'IN',
    displayName: 'Агра, Уттар-Прадеш, Индия',
    lon: 78.0081,
    lat: 27.1767,
    popularity: 8.0,
  },

  // ─── ИНДОНЕЗИЯ ───────────────────────────────────────────────────────────
  {
    nameRu: 'Бали',
    aliases: 'Bali,DPS',
    type: 'island',
    countryCode: 'ID',
    displayName: 'Бали, Индонезия',
    lon: 115.092,
    lat: -8.3405,
    popularity: 9.5,
  },
  {
    nameRu: 'Убуд',
    aliases: 'Ubud',
    type: 'resort',
    countryCode: 'ID',
    displayName: 'Убуд, Бали, Индонезия',
    lon: 115.2624,
    lat: -8.5069,
    popularity: 8.0,
  },
  {
    nameRu: 'Семиньяк',
    aliases: 'Seminyak',
    type: 'resort',
    countryCode: 'ID',
    displayName: 'Семиньяк, Бали, Индонезия',
    lon: 115.1572,
    lat: -8.6906,
    popularity: 7.5,
  },
  {
    nameRu: 'Джакарта',
    aliases: 'Jakarta,CGK',
    type: 'city',
    countryCode: 'ID',
    displayName: 'Джакарта, Индонезия',
    lon: 106.8456,
    lat: -6.2088,
    popularity: 7.5,
  },

  // ─── ШРИ-ЛАНКА ───────────────────────────────────────────────────────────
  {
    nameRu: 'Коломбо',
    aliases: 'Colombo,CMB',
    type: 'city',
    countryCode: 'LK',
    displayName: 'Коломбо, Шри-Ланка',
    lon: 79.8612,
    lat: 6.9271,
    popularity: 7.5,
  },
  {
    nameRu: 'Канди',
    aliases: 'Kandy',
    type: 'city',
    countryCode: 'LK',
    displayName: 'Канди, Шри-Ланка',
    lon: 80.6337,
    lat: 7.2906,
    popularity: 7.5,
  },
  {
    nameRu: 'Мирисса',
    aliases: 'Mirissa',
    type: 'resort',
    countryCode: 'LK',
    displayName: 'Мирисса, Шри-Ланка',
    lon: 80.4521,
    lat: 5.9483,
    popularity: 7.0,
  },
  {
    nameRu: 'Унаватуна',
    aliases: 'Unawatuna',
    type: 'resort',
    countryCode: 'LK',
    displayName: 'Унаватуна, Шри-Ланка',
    lon: 80.4264,
    lat: 6.0103,
    popularity: 7.0,
  },

  // ─── МАЛЬДИВЫ ────────────────────────────────────────────────────────────
  {
    nameRu: 'Мальдивы',
    aliases: 'Maldives,Мальдивские острова',
    type: 'country',
    countryCode: 'MV',
    displayName: 'Мальдивы',
    lon: 73.2207,
    lat: 3.2028,
    popularity: 9.0,
  },
  {
    nameRu: 'Мале',
    aliases: 'Male,MLE',
    type: 'city',
    countryCode: 'MV',
    displayName: 'Мале, Мальдивы',
    lon: 73.5093,
    lat: 4.1755,
    popularity: 8.0,
  },

  // ─── ЕВРОПА ───────────────────────────────────────────────────────────────
  {
    nameRu: 'Париж',
    aliases: 'Paris,CDG,ORY',
    type: 'city',
    countryCode: 'FR',
    displayName: 'Париж, Франция',
    lon: 2.3522,
    lat: 48.8566,
    popularity: 9.5,
  },
  {
    nameRu: 'Лондон',
    aliases: 'London,LHR,LGW',
    type: 'city',
    countryCode: 'GB',
    displayName: 'Лондон, Великобритания',
    lon: -0.1278,
    lat: 51.5074,
    popularity: 9.5,
  },
  {
    nameRu: 'Рим',
    aliases: 'Rome,Roma,FCO',
    type: 'city',
    countryCode: 'IT',
    displayName: 'Рим, Италия',
    lon: 12.4964,
    lat: 41.9028,
    popularity: 9.0,
  },
  {
    nameRu: 'Барселона',
    aliases: 'Barcelona,BCN',
    type: 'city',
    countryCode: 'ES',
    displayName: 'Барселона, Испания',
    lon: 2.1734,
    lat: 41.3851,
    popularity: 9.0,
  },
  {
    nameRu: 'Мадрид',
    aliases: 'Madrid,MAD',
    type: 'city',
    countryCode: 'ES',
    displayName: 'Мадрид, Испания',
    lon: -3.7038,
    lat: 40.4168,
    popularity: 8.5,
  },
  {
    nameRu: 'Берлин',
    aliases: 'Berlin,BER',
    type: 'city',
    countryCode: 'DE',
    displayName: 'Берлин, Германия',
    lon: 13.405,
    lat: 52.52,
    popularity: 8.5,
  },
  {
    nameRu: 'Амстердам',
    aliases: 'Amsterdam,AMS',
    type: 'city',
    countryCode: 'NL',
    displayName: 'Амстердам, Нидерланды',
    lon: 4.9041,
    lat: 52.3676,
    popularity: 8.5,
  },
  {
    nameRu: 'Вена',
    aliases: 'Vienna,Wien,VIE',
    type: 'city',
    countryCode: 'AT',
    displayName: 'Вена, Австрия',
    lon: 16.3738,
    lat: 48.2082,
    popularity: 8.5,
  },
  {
    nameRu: 'Прага',
    aliases: 'Prague,Praha,PRG',
    type: 'city',
    countryCode: 'CZ',
    displayName: 'Прага, Чехия',
    lon: 14.4378,
    lat: 50.0755,
    popularity: 8.5,
  },
  {
    nameRu: 'Будапешт',
    aliases: 'Budapest,BUD',
    type: 'city',
    countryCode: 'HU',
    displayName: 'Будапешт, Венгрия',
    lon: 19.0402,
    lat: 47.4979,
    popularity: 8.0,
  },
  {
    nameRu: 'Варшава',
    aliases: 'Warsaw,Warszawa,WAW',
    type: 'city',
    countryCode: 'PL',
    displayName: 'Варшава, Польша',
    lon: 21.0122,
    lat: 52.2297,
    popularity: 7.5,
  },
  {
    nameRu: 'Краков',
    aliases: 'Krakow,Kraków,KRK',
    type: 'city',
    countryCode: 'PL',
    displayName: 'Краков, Польша',
    lon: 19.9449,
    lat: 50.0647,
    popularity: 7.5,
  },
  {
    nameRu: 'Черногория',
    aliases: 'Montenegro',
    type: 'country',
    countryCode: 'ME',
    displayName: 'Черногория',
    lon: 19.3744,
    lat: 42.7087,
    popularity: 8.0,
  },
  {
    nameRu: 'Будва',
    aliases: 'Budva',
    type: 'resort',
    countryCode: 'ME',
    displayName: 'Будва, Черногория',
    lon: 18.8389,
    lat: 42.2864,
    popularity: 8.0,
  },
  {
    nameRu: 'Котор',
    aliases: 'Kotor',
    type: 'city',
    countryCode: 'ME',
    displayName: 'Котор, Черногория',
    lon: 18.7714,
    lat: 42.4247,
    popularity: 8.0,
  },
  {
    nameRu: 'Подгорица',
    aliases: 'Podgorica,TGD',
    type: 'city',
    countryCode: 'ME',
    displayName: 'Подгорица, Черногория',
    lon: 19.2636,
    lat: 42.4304,
    popularity: 7.0,
  },
  {
    nameRu: 'Белград',
    aliases: 'Belgrade,Beograd,BEG',
    type: 'city',
    countryCode: 'RS',
    displayName: 'Белград, Сербия',
    lon: 20.4651,
    lat: 44.8176,
    popularity: 7.5,
  },
  {
    nameRu: 'Дубровник',
    aliases: 'Dubrovnik,DBV',
    type: 'resort',
    countryCode: 'HR',
    displayName: 'Дубровник, Хорватия',
    lon: 18.0944,
    lat: 42.6507,
    popularity: 8.5,
  },
  {
    nameRu: 'Сплит',
    aliases: 'Split,SPU',
    type: 'city',
    countryCode: 'HR',
    displayName: 'Сплит, Хорватия',
    lon: 16.4402,
    lat: 43.5081,
    popularity: 8.0,
  },
  {
    nameRu: 'Афины',
    aliases: 'Athens,Athina,ATH',
    type: 'city',
    countryCode: 'GR',
    displayName: 'Афины, Греция',
    lon: 23.7275,
    lat: 37.9838,
    popularity: 8.5,
  },
  {
    nameRu: 'Санторини',
    aliases: 'Santorini,JTR,Тира',
    type: 'island',
    countryCode: 'GR',
    displayName: 'Санторини, Греция',
    lon: 25.4615,
    lat: 36.3932,
    popularity: 9.0,
  },
  {
    nameRu: 'Крит',
    aliases: 'Crete,HER,Ираклион',
    type: 'island',
    countryCode: 'GR',
    displayName: 'Крит, Греция',
    lon: 24.8093,
    lat: 35.2401,
    popularity: 8.5,
  },
  {
    nameRu: 'Корфу',
    aliases: 'Corfu,Kerkyra,CFU',
    type: 'island',
    countryCode: 'GR',
    displayName: 'Корфу, Греция',
    lon: 19.9211,
    lat: 39.6243,
    popularity: 8.0,
  },
  {
    nameRu: 'Ницца',
    aliases: 'Nice,NCE',
    type: 'resort',
    countryCode: 'FR',
    displayName: 'Ницца, Лазурный берег, Франция',
    lon: 7.262,
    lat: 43.7102,
    popularity: 8.0,
  },
  {
    nameRu: 'Монако',
    aliases: 'Monaco,MCM',
    type: 'city',
    countryCode: 'MC',
    displayName: 'Монако',
    lon: 7.4246,
    lat: 43.7384,
    popularity: 8.0,
  },
  {
    nameRu: 'Венеция',
    aliases: 'Venice,Venezia,VCE',
    type: 'city',
    countryCode: 'IT',
    displayName: 'Венеция, Италия',
    lon: 12.3155,
    lat: 45.4408,
    popularity: 9.0,
  },
  {
    nameRu: 'Милан',
    aliases: 'Milan,Milano,MXP,LIN',
    type: 'city',
    countryCode: 'IT',
    displayName: 'Милан, Италия',
    lon: 9.19,
    lat: 45.4654,
    popularity: 8.5,
  },
  {
    nameRu: 'Флоренция',
    aliases: 'Florence,Firenze,FLR',
    type: 'city',
    countryCode: 'IT',
    displayName: 'Флоренция, Италия',
    lon: 11.2558,
    lat: 43.7696,
    popularity: 8.5,
  },
  {
    nameRu: 'Хельсинки',
    aliases: 'Helsinki,HEL',
    type: 'city',
    countryCode: 'FI',
    displayName: 'Хельсинки, Финляндия',
    lon: 24.9384,
    lat: 60.1699,
    popularity: 7.5,
  },
  {
    nameRu: 'Таллин',
    aliases: 'Tallinn,TLL',
    type: 'city',
    countryCode: 'EE',
    displayName: 'Таллин, Эстония',
    lon: 24.7536,
    lat: 59.437,
    popularity: 7.5,
  },
  {
    nameRu: 'Рига',
    aliases: 'Riga,RIX',
    type: 'city',
    countryCode: 'LV',
    displayName: 'Рига, Латвия',
    lon: 24.1052,
    lat: 56.946,
    popularity: 7.5,
  },
  {
    nameRu: 'Вильнюс',
    aliases: 'Vilnius,VNO',
    type: 'city',
    countryCode: 'LT',
    displayName: 'Вильнюс, Литва',
    lon: 25.2799,
    lat: 54.6872,
    popularity: 7.0,
  },

  // ─── БЛИЖНИЙ ВОСТОК ───────────────────────────────────────────────────────
  {
    nameRu: 'Иерусалим',
    aliases: 'Jerusalem,JRS',
    type: 'city',
    countryCode: 'IL',
    displayName: 'Иерусалим, Израиль',
    lon: 35.2137,
    lat: 31.7683,
    popularity: 8.5,
  },
  {
    nameRu: 'Тель-Авив',
    aliases: 'Tel Aviv,TLV',
    type: 'city',
    countryCode: 'IL',
    displayName: 'Тель-Авив, Израиль',
    lon: 34.7818,
    lat: 32.0853,
    popularity: 8.0,
  },
  {
    nameRu: 'Эйлат',
    aliases: 'Eilat,ETH',
    type: 'resort',
    countryCode: 'IL',
    displayName: 'Эйлат, Израиль',
    lon: 34.9519,
    lat: 29.5581,
    popularity: 7.5,
  },

  // ─── АФРИКА ───────────────────────────────────────────────────────────────
  {
    nameRu: 'Марракеш',
    aliases: 'Marrakesh,Marrakech,RAK',
    type: 'city',
    countryCode: 'MA',
    displayName: 'Марракеш, Марокко',
    lon: -7.9811,
    lat: 31.6295,
    popularity: 8.0,
  },
  {
    nameRu: 'Касабланка',
    aliases: 'Casablanca,CMN',
    type: 'city',
    countryCode: 'MA',
    displayName: 'Касабланка, Марокко',
    lon: -7.5898,
    lat: 33.5731,
    popularity: 7.5,
  },

  // ─── СЕВЕРНАЯ АМЕРИКА ────────────────────────────────────────────────────
  {
    nameRu: 'Нью-Йорк',
    aliases: 'New York,NYC,JFK,EWR',
    type: 'city',
    countryCode: 'US',
    displayName: 'Нью-Йорк, США',
    lon: -74.006,
    lat: 40.7128,
    popularity: 9.0,
  },
  {
    nameRu: 'Лос-Анджелес',
    aliases: 'Los Angeles,LAX,LA',
    type: 'city',
    countryCode: 'US',
    displayName: 'Лос-Анджелес, США',
    lon: -118.2437,
    lat: 34.0522,
    popularity: 8.5,
  },
  {
    nameRu: 'Майами',
    aliases: 'Miami,MIA',
    type: 'city',
    countryCode: 'US',
    displayName: 'Майами, Флорида, США',
    lon: -80.1918,
    lat: 25.7617,
    popularity: 8.5,
  },
  {
    nameRu: 'Лас-Вегас',
    aliases: 'Las Vegas,LAS',
    type: 'city',
    countryCode: 'US',
    displayName: 'Лас-Вегас, Невада, США',
    lon: -115.1398,
    lat: 36.1699,
    popularity: 8.5,
  },
  {
    nameRu: 'Торонто',
    aliases: 'Toronto,YYZ',
    type: 'city',
    countryCode: 'CA',
    displayName: 'Торонто, Онтарио, Канада',
    lon: -79.3832,
    lat: 43.6532,
    popularity: 7.5,
  },
  {
    nameRu: 'Мехико',
    aliases: 'Mexico City,MEX,Ciudad de Mexico',
    type: 'city',
    countryCode: 'MX',
    displayName: 'Мехико, Мексика',
    lon: -99.1332,
    lat: 19.4326,
    popularity: 7.5,
  },
  {
    nameRu: 'Канкун',
    aliases: 'Cancun,CUN',
    type: 'resort',
    countryCode: 'MX',
    displayName: 'Канкун, Мексика',
    lon: -86.8515,
    lat: 21.1619,
    popularity: 8.0,
  },

  // ─── ЛАТИНСКАЯ АМЕРИКА ───────────────────────────────────────────────────
  {
    nameRu: 'Рио-де-Жанейро',
    aliases: 'Rio de Janeiro,GIG,SDU,Рио',
    type: 'city',
    countryCode: 'BR',
    displayName: 'Рио-де-Жанейро, Бразилия',
    lon: -43.1729,
    lat: -22.9068,
    popularity: 8.5,
  },
  {
    nameRu: 'Буэнос-Айрес',
    aliases: 'Buenos Aires,EZE,AEP',
    type: 'city',
    countryCode: 'AR',
    displayName: 'Буэнос-Айрес, Аргентина',
    lon: -58.3816,
    lat: -34.6037,
    popularity: 8.0,
  },
  {
    nameRu: 'Куба',
    aliases: 'Cuba,Гавана,Havana,HAV',
    type: 'country',
    countryCode: 'CU',
    displayName: 'Куба',
    lon: -79.5,
    lat: 22.0,
    popularity: 7.5,
  },

  // ─── КЫРГЫЗСТАН, ТАДЖИКИСТАН ─────────────────────────────────────────────
  {
    nameRu: 'Бишкек',
    aliases: 'Bishkek,FRU',
    type: 'city',
    countryCode: 'KG',
    displayName: 'Бишкек, Кыргызстан',
    lon: 74.5698,
    lat: 42.8746,
    popularity: 7.0,
  },
  {
    nameRu: 'Иссык-Куль',
    aliases: 'Issyk-Kul,Иссык Куль',
    type: 'region',
    countryCode: 'KG',
    displayName: 'Иссык-Куль, Кыргызстан',
    lon: 77.5,
    lat: 42.45,
    popularity: 7.5,
  },
  {
    nameRu: 'Душанбе',
    aliases: 'Dushanbe,DYU',
    type: 'city',
    countryCode: 'TJ',
    displayName: 'Душанбе, Таджикистан',
    lon: 68.7864,
    lat: 38.5598,
    popularity: 6.0,
  },
];
