import { Injectable, Logger } from '@nestjs/common';
import type { ChatCompletionMessageParam } from 'openai/resources/chat/completions';
import type { ParsedIntent } from '../types/pipeline.types';
import type {
  FilteredPoi,
  LlmGeneratedPoiResponse,
  PoiItem,
} from '../types/poi.types';
import { LlmClientService } from './llm-client.service';

interface LlmPoiSelection {
  id: string;
  description?: string;
  reason?: string;
}

interface ExtendedFilteredPoiResponse {
  selected?: LlmPoiSelection[];
  rankedPois?: LlmPoiSelection[];
}

@Injectable()
export class SemanticFilterService {
  private readonly logger = new Logger('AI_PIPELINE:SemanticFilter');

  constructor(private readonly llmClientService: LlmClientService) {}

  private safeParseJson<T>(content: string | null): T {
    if (!content) return {} as T;
    let clean = content.trim();
    // Убираем возможную разметку markdown
    clean = clean.replace(/^```(?:json)?\s*/i, '').replace(/\s*```$/i, '');
    // Убираем висящие запятые (trailing commas), которые GPT-4o-mini часто оставляет
    clean = clean.replace(/,\s*([\]}])/g, '$1');
    try {
      return JSON.parse(clean) as T;
    } catch (error) {
      this.logger.error(
        `[safeParseJson] Error parsing JSON: ${error}. Raw content: ${content.substring(0, 100)}...`,
      );
      return {} as T;
    }
  }

  async select(
    pois: PoiItem[],
    intent: ParsedIntent,
    fallbacks: string[],
  ): Promise<FilteredPoi[]> {
    if (pois.length === 0) {
      return this.generatePoiFromScratch(intent);
    }

    const isCis = this.llmClientService.isCisRegion(
      intent.country_code,
      intent.city,
    );

    const messages: ChatCompletionMessageParam[] = [
      {
        role: 'system',
        content:
          'Ты — эксперт по планированию путешествий. Твоя задача — отобрать и отранжировать лучшие места для туриста. Верни ответ СТРОГО в формате JSON. Не используй лишних слов, пояснений и разметки markdown вне JSON. СТРОГО соблюдай синтаксис JSON: никаких лишних запятых перед закрывающими скобками.',
      },
      {
        role: 'user',
        content: this.buildPrompt(pois, intent),
      },
    ];

    try {
      const content = await this.llmClientService.chat(messages, {
        jsonMode: true,
        isCis,
        maxTokens: 3000,
      });

      const parsed = this.safeParseJson<ExtendedFilteredPoiResponse>(content);
      const selectedRaw = Array.isArray(parsed.selected)
        ? parsed.selected
        : Array.isArray(parsed.rankedPois)
          ? parsed.rankedPois
          : [];

      return selectedRaw
        .map((item) => {
          const original = this.resolvePoiByModelId(pois, item.id);
          if (!original) return null;
          return {
            ...original,
            description:
              item.description || item.reason || original.description || '',
          };
        })
        .filter((item): item is FilteredPoi => item !== null);
    } catch (error: any) {
      this.logger.error(`Semantic filter failed: ${error.message}`);
      fallbacks.push('SEMANTIC_FILTER_FAILED');
      return pois
        .slice(0, 15)
        .map((poi) => ({ ...poi, description: poi.description || poi.name }));
    }
  }

  async generatePoiFromScratch(intent: ParsedIntent): Promise<FilteredPoi[]> {
    const target = intent.poi_count_requested ?? Math.min(intent.days * 6, 20);
    const citiesRaw = [
      (intent as any).city_from,
      intent.city,
      (intent as any).city_to,
    ].filter(Boolean);
    const uniqueCities = Array.from(new Set(citiesRaw)).join(' - ');
    const prompt = `Ты рекомендуешь туристические места по маршруту ${uniqueCities}. Предпочтения: ${intent.preferences_text}. Нужно мест: ${target}. Верни JSON: {"selected": [{"id": "unique_id", "name": "Название", "category": "attraction", "rating": 4.5, "description": "Описание"}]}`;

    const isCis = this.llmClientService.isCisRegion(
      intent.country_code,
      intent.city,
    );

    try {
      const content = await this.llmClientService.chat(
        [{ role: 'user', content: prompt }],
        {
          temperature: 0.3,
          isCis,
          jsonMode: true,
        },
      );

      const parsed = this.safeParseJson<LlmGeneratedPoiResponse>(content);

      return (parsed.selected || [])
        .map(
          (item) =>
            ({
              id: item.id,
              name: item.name || 'Unknown POI',
              category: item.category || 'attraction',
              rating: item.rating ?? 4.0,
              description: item.description || '',
              address: 'Generated by LLM',
              coordinates: { lat: 0, lon: 0 },
              ai_generated: true,
              needs_geocoding: true,
            }) as FilteredPoi,
        )
        .slice(0, target);
    } catch (error) {
      this.logger.error(`[generatePoiFromScratch] Error: ${error}`);
      return [];
    }
  }

  async compareProviders(
    pois: PoiItem[],
    intent: ParsedIntent,
  ): Promise<{
    yandex: { pois: FilteredPoi[]; error?: string; duration_ms: number };
    openrouter: { pois: FilteredPoi[]; error?: string; duration_ms: number };
  }> {
    const [yandexResult, openrouterResult] = await Promise.allSettled([
      (async () => {
        const t0 = Date.now();
        const res = await this.selectWithProvider(pois, intent, 'yandex');
        return { pois: res, duration_ms: Date.now() - t0 };
      })(),
      (async () => {
        const t0 = Date.now();
        const res = await this.selectWithProvider(pois, intent, 'openrouter');
        return { pois: res, duration_ms: Date.now() - t0 };
      })(),
    ]);

    const toResult = (
      r: PromiseSettledResult<{ pois: FilteredPoi[]; duration_ms: number }>,
    ) =>
      r.status === 'fulfilled'
        ? r.value
        : {
            pois: [],
            error: String(r.reason),
            duration_ms: 0,
          };

    return {
      yandex: toResult(yandexResult),
      openrouter: toResult(openrouterResult),
    };
  }

  private async selectWithProvider(
    pois: PoiItem[],
    intent: ParsedIntent,
    provider: 'openrouter' | 'yandex',
  ): Promise<FilteredPoi[]> {
    const messages: ChatCompletionMessageParam[] = [
      {
        role: 'system',
        content:
          'Ты — эксперт по планированию путешествий. Твоя задача — отобрать и отранжировать лучшие места для туриста. Верни ответ СТРОГО в формате JSON. Не используй лишних слов, пояснений и разметки markdown вне JSON. СТРОГО соблюдай синтаксис JSON: никаких лишних запятых перед закрывающими скобками.',
      },
      {
        role: 'user',
        content: this.buildPrompt(pois, intent),
      },
    ];

    const content = await this.llmClientService.chat(messages, {
      jsonMode: true,
      provider,
      maxTokens: 3000,
    });

    const parsed = this.safeParseJson<ExtendedFilteredPoiResponse>(content);
    const selectedRaw = Array.isArray(parsed.selected)
      ? parsed.selected
      : Array.isArray(parsed.rankedPois)
        ? parsed.rankedPois
        : [];

    return selectedRaw
      .map((item) => {
        const original = this.resolvePoiByModelId(pois, item.id);
        if (!original) return null;
        return {
          ...original,
          description:
            item.description || item.reason || original.description || '',
        };
      })
      .filter((item): item is FilteredPoi => item !== null);
  }

  private buildPrompt(pois: PoiItem[], intent: ParsedIntent): string {
    const days = intent.days || 1;
    const targetCount = days * 4 + 8;

    const citiesRaw = [
      (intent as any).city_from,
      intent.city,
      (intent as any).city_to,
    ].filter(Boolean);
    const uniqueCities = Array.from(new Set(citiesRaw)).join(' - ');

    return `Ты — эксперт по туризму. Твоя задача — выбрать лучшие места из предложенного списка по маршруту ${uniqueCities}.
ПРАВИЛА RESERVE POOL:
1. Выбери ровно ${targetCount} лучших мест.
2. Первые ${days * 4} мест — идеальный выбор. Остальные — резерв.
3. Отранжируй от самого важного (rank 1).
УЧИТЫВАЙ ПРЕДПОЧТЕНИЯ: "${intent.preferences_text}"
БЮДЖЕТ: ${intent.budget_total || 'не указан'}

СПИСОК МЕСТ (ID: Название):
${pois.map((p, i) => `${i + 1}: ${p.name} (${p.category}, рейтинг ${p.rating})`).join('\n')}

ВЕРНИ ТОЛЬКО JSON:
{
  "rankedPois": [
    { "id": "номер_из_списка", "rank": 1, "reason": "Краткое описание фишки места." }
  ]
}`;
  }

  private resolvePoiByModelId(
    pois: PoiItem[],
    rawId: string,
  ): PoiItem | undefined {
    const id = String(rawId).trim();
    const index = parseInt(id, 10);
    if (!isNaN(index) && index >= 1 && index <= pois.length)
      return pois[index - 1];
    return pois.find((p) => p.id === id);
  }
}
